version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

build_script:
  - ps: ./build/build.ps1 -skip

test_script:
  - ps: ./build/test.ps1
    
deploy_script:
  - ps: ./build/deploy.ps1

artifacts:
  - path: '**\*.nupkg'