name: .NET Core

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build with dotnet
        run: dotnet build -c Release
      - name: Push to nuget
        run: dotnet nuget push src/OpayCashier/bin/Release/OPay.Cashier.1.0.0.nupkg -k oy2kze6zpjoxuiu74adqmu476kun4olulmntiozobzj2o4 -s https://api.nuget.org/v3/index.json